"""Historical task corpus for planner/execution-policy evaluations."""

from __future__ import annotations

TASKS = [
    "Read the medication bottle label.",
    "Read the expiration date.",
    "Read a restaurant menu.",
    "Read a street sign.",
    "Read the ingredients on a food package.",
    "Read a handwritten note.",
    "Read the text on a computer screen.",
    "Read the instructions on an appliance.",
    "Find my cup.",
    "Find my phone.",
    "Locate my keys.",
    "Find the remote control.",
    "Find the door handle.",
    "Find an empty chair.",
    "Find the elevator button.",
    "Find the traffic light.",
    "Locate the correct medication bottle.",
    "Find the nearest trash can.",
    "Describe the position of the chair relative to the table.",
    "Tell me whether the cup is to the left or right of the bottle.",
    "Describe where the door is.",
    "Tell me how far away the stairs are.",
    "Describe obstacles in front of me.",
    "Explain the layout of the room.",
    "Tell me whether the chair is behind the desk.",
    "Describe the distance between me and the crosswalk.",
    "Guide me to the building entrance.",
    "Help me find the nearest exit.",
    "Guide me to an available seat.",
    "Navigate me to the checkout counter.",
    "Help me reach the elevator.",
    "Guide me to the correct bus stop.",
    "Help me cross the street safely.",
    "Navigate me through a crowded hallway.",
    "Describe what is happening in front of me.",
    "Explain the scene around me.",
    "Tell me whether it is safe to cross the street.",
    "Describe the activity in the room.",
    "Explain what the people are doing.",
    "Tell me whether this outfit matches.",
    "Describe the overall environment.",
    "Explain whether the stove appears to be on.",
    "Interpret this map.",
    "Explain this chart.",
    "Read the schedule on this screen.",
    "Interpret a bus timetable.",
    "Explain a webpage layout.",
    "Read a departure board.",
    "Interpret a weather chart.",
    "Read a calendar.",
    "Tell me whether I am moving toward the object.",
    "Guide my camera toward the target.",
    "Help me center the object in view.",
    "Tell me how to adjust the camera.",
    "Explain whether I am getting closer to the door.",
    "Guide me to align with the crosswalk.",
    "Summarize what happened in this video.",
    "Describe the actions occurring in the video.",
    "Explain the sequence of events.",
    "Track a person's activities.",
    "Describe changes in the environment.",
    "Summarize the interaction between people.",
    "Find the passenger door handle.",
    "Find my Uber.",
    "Locate the correct medication bottle.",
    "Guide me to an empty seat.",
    "Tell me whether it is safe to cross the street.",
    "Help me find the checkout counter.",
    "Find the elevator and guide me to it.",
    "Locate the restroom entrance.",
    "Find the nearest available parking space.",
    "Identify the correct bus and tell me where the entrance is.",
]


__all__ = ["TASKS"]
